# Generated by Django 5.1.2 on 2024-12-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("telegram_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=50)),
                ("weight", models.IntegerField(null=True)),
                ("activity_level", models.FloatField(null=True)),
                ("goal", models.IntegerField(null=True)),
                ("calories", models.FloatField(null=True)),
                ("carbs", models.FloatField(blank=True, null=True)),
                ("fats", models.FloatField(blank=True, null=True)),
                ("proteins", models.FloatField(blank=True, null=True)),
                (
                    "no_products",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "yes_products",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("allergies", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "menu_generator",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="coachbot.coach",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("technique", models.TextField(blank=True)),
                ("sets", models.PositiveIntegerField(blank=True, null=True)),
                ("repetitions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "muscle_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="coachbot.musclegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="coachbot.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_programs",
                        to="coachbot.client",
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="training_programs", to="coachbot.exercise"
                    ),
                ),
            ],
        ),
    ]
