# Generated by Django 5.1.8 on 2025-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='positioning',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
