# Generated by Django 5.1.2 on 2024-12-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coachbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="repetitions",
            new_name="reps",
        ),
    ]
