# Generated by Django 5.1.2 on 2025-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coachbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
