# Generated by Django 5.1.2 on 2024-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coachbot", "0003_alter_client_goal_alter_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="allergies",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="menu_generator",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="no_products",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="yes_products",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
