# Generated by Django 5.1.2 on 2025-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coachbot",
            "0004_alter_client_allergies_alter_client_menu_generator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="field",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
